### ISSUE TITLE
Running Tests fails on missing directives

### ISSUE THREAD

**Issue by Kylex87** [sarahdayan/star-rating-vue-js-tutorial#1]
Hi,

can't go through tutorial because there are missing directives for test. Is a file missing in the repository? Seems like he searches it in 'src/directives/test.js' . Same problem in both branches. See the attached log message.

Sorry if the fix is obvious, but I'm new to Vue.js and wanted to use your project/tutorial for TDD in order to learn Vue.js.

``npm run test:unit

> star-rating-vue-js-tutorial@0.1.0 test:unit /home/XXX/projects/star-rating-vue-js-tutorial
> vue-cli-service test:unit

 FAIL  tests/unit/Rating.spec.js
  ● Test suite failed to run

    Configuration error:
    
    Could not locate module @/directives/test.js mapped as:
    /home/XXX/projects/star-rating-vue-js-tutorial/src/directives/test.js.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^@\/(.*)$/": "/home/XXX/projects/star-rating-vue-js-tutorial/src/$1"
      },
      "resolver": null
    }

      16 | import Icon from 'vue-awesome/components/Icon'
      17 | 
    > 18 | import Test from '@/directives/test.js'
         | ^
      19 | 
      20 | export default {
      21 |   components: { Icon },

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:411:17)
      at src/components/Rating.vue:18:1
      at Object.<anonymous> (src/components/Rating.vue:65:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.82s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! star-rating-vue-js-tutorial@0.1.0 test:unit: `vue-cli-service test:unit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the star-rating-vue-js-tutorial@0.1.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/XXX/.npm/_logs/2018-10-16T08_53_53_364Z-debug.log
``

**Comment by sarahdayan** [comment]
Oops, sorry for this, removed it from `master` and totally forgot to add it to `tests`.

Fixed it with e5ef44a6e8440dedfa45f3c8f8030dbd200a54f8. You can pull the `tests` branch, this should be good now.
